Assignments
LaunchCodeEducation/data-analysis pull request #46
Opened 2022-08-12 17:27 UTC by codinglikeagirl42

To Check Assignments 2, 3 and 4 and Instruction for Using Github w/Jupyter Notebooks.

2022-08-12 20:29 UTC, gildedgardenia requested changes
Overall, I think you did a good job with this! When reviewing it, I noticed some grammatical errors. Other than that, I have some suggestions that might ease readability for some of our students.

1. Break Assignment 4 into multiple pages with one page per checkpoint. We have done this with larger assignments and it can really students understand how the assignment breaks down into separate pieces.
2. I suggest you review your alt text. If I closed my eyes and someone read it to me, I would not be able to put together what the image is about. Descriptors like "a screenshot" can be removed entirely. In your alt text, you also used the phrase "what you'll see" which considering the target audience for alt text is visually impaired users is a poor choice of words.

2022-08-12 20:47 UTC, codinglikeagirl42 commented on src/assignments/call-center-cleanup.rst
> +:ref:`Instruction for Using Github w/Jupyter Notebooks<usingGitHubNotebooks>`. Follow the
Did this not build correctly for you?  The syntax for :ref:`link to a different section<Cross-References to Locations in the Same Document>`. There isn't suppose to be a space.

2022-08-15 19:56 UTC, codinglikeagirl42 commented on src/appendices/jupyter-notebooks/using-github-notebooks.rst
> +    - Switch into my new project folder
I've added syntax highlighting and changed Codergirl to Women+ in both terminal images.

2022-08-15 20:36 UTC, codinglikeagirl42 commented
Thank you Sally for the review and great insights.  I've fixed the alt text to better reflect the images. 

I originally had Assignment 4 broken down into individual pages for each checkpoint but did not like how it flowed.  I prefer it on on page and have created links at the very top that would take you to each checkpoint.  There are links after each checkpoint that take you back to the top.  This helps keep the idea of one cohesive final project.

2022-08-16 17:47 UTC, codinglikeagirl42 commented
Separated out final project into individual pages.  Will add links to samples in different PR

2022-08-16 18:13 UTC, merged