Chap27
LaunchCodeEducation/data-analysis pull request #70
Opened 2022-11-14 15:56 UTC by codinglikeagirl42

2022-11-17 21:05 UTC, gildedgardenia requested changes
The formatting is inconsistent and CSV needs to be capitalized. Please review each page carefully before re-submitting.

2022-12-07 19:53 UTC, gildedgardenia approved these changes
Approved! Got some final suggestions for you!

2022-12-07 19:53 UTC, gildedgardenia commented on src/chapters/tableau-part3/studio.rst
> +Download `Retail Data Analytics data set <https://www.kaggle.com/datasets/manjeetsingh/retaildataset?select=Features+data+set.csv>`__. There are 3 csv files. To download all csv files at once, click
```suggestion
Download `Retail Data Analytics data set <https://www.kaggle.com/datasets/manjeetsingh/retaildataset?select=Features+data+set.csv>`__. There are 3 CSV files. To download all CSV files at once, click on the ``Download`` bubble next to the ``New Notebook`` bubble.  An orange arrow is pointing to the ``Download`` bubble in the image below.
```

2022-12-07 19:53 UTC, gildedgardenia commented on src/chapters/tableau-part3/studio.rst
> +#. Open the csv file in Tableau Public.
```suggestion
#. Open the CSV file in Tableau Public.  
```

2022-12-07 19:53 UTC, gildedgardenia commented on src/chapters/tableau-part3/studio.rst
> +   #. Each csv has a ``Store`` column.
```suggestion
   #. Each CSV has a ``Store`` column.
```

2022-12-07 19:53 UTC, gildedgardenia commented on src/chapters/tableau-part3/studio.rst
> +| Before you turn in your vizzes:
```suggestion
Before you turn in your vizzes:
```

2022-12-07 19:53 UTC, gildedgardenia commented on src/chapters/tableau-part3/tableau-part3.rst
> +| The calculation videos are part of a larger calculations playlist.  We suggest you explore more videos in this playlist to learn more about calculations with certain data types and in specific situ
```suggestion
Watch the following videos to help you learn about Tableau calculations functionality and syntax, as well as parameters.   

The calculation videos are part of a larger calculations playlist.  We suggest you explore more videos in this playlist to learn more about calculations with certain data types and in specific situations.  Keep in mind that we will not be covering LOD (Level of Detail) calculations in this class, so you may skip over those.
```

2022-12-09 18:43 UTC, codinglikeagirl42 commented on src/chapters/tableau-part3/exercises.rst
> +      #. Hint: You can use a quick calculation for this.
Courtney Can you take a look at this.

2022-12-12 20:46 UTC, merged